### ISSUE TITLE
기능 ToDo 리스트 (M-Music 프로젝트)

### ISSUE THREAD

**Issue by rkstpwlwo** [codestates/Boys4Men#4]
## 1. 시스템 아키텍처
- [ ]  JWT를 이용한 로그인 구현 | 필수 | ★

## 2. UI/UX
- [ ] 회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 기능 구현 | 필수 | 프론트엔드, 백엔드 | ★ |  
- [ ]  회원가입, 로그인 및 회원정보 수정 시 유효성 검사 | 필수 | 프론트엔드 | ★ |  
- [ ] 소셜 로그인 외 서비스 자체 회원가입 기능 제공 | 필수 | 프론트엔드 | ★
- [ ] 회원 탈퇴나 리소스 삭제시 확인(confirm) 모달 제공 | 권장 | 프론트엔드 | ★
- [ ]  마이페이지를 통해 사용자 개인정보 수정 기능 제공 | 필수 | 프론트엔드 | ★ |  
- [ ]  (소셜 로그인이 아닐 경우) 비밀번호 수정 기능 제공 | 필수 | 프론트엔드 | ★
- [ ]  라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다룬 것) | 필수 | ★
- [ ]  라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다루지 않은 것) | 권장 | ★★★

## 3. 스키마 및 API
- [ ] N:M (다대다) 관계 설정 | 필수 | ★
- [ ]  ERD (DB Diagram) 작성 | 필수 | ★
- [ ]  API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★
- [ ]  ORM 사용 (sequelize) | 권장 | ★

## 4. DevOps
- [ ]  [코드] precommit 단계에서 semistandard 적용 | 필수 | ★
- [ ]  [릴리즈] 깃허브 커밋 메세지 규칙 합의 | 필수 | ★
- [ ]  [코드] 버전 규칙 합의 | 필수 | ★
- [ ]  [릴리즈] PR 형식 합의 | 권장 | ★
- [ ]  [배포] 배포 자동화 설정 | 권장 | ★
- [ ]  [배포] 도메인 구매 및 HTTPS 배포 | 권장 | ★★★

## Advanced (도전) 항목을 추가적으로 구현할 계획이라면, 아래에 적어주세요
- [ ] MBTI 유형별 추천 음악 관련 공연 정보 및 공연장 위치 안내 지도

#### 신중 항목은 이번에는 구현하지 않겠습니다!
